### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by 2826430176** [18351089214/qzone#1]
大佬可以分享下逆向qq的过程嘛，本人刚刚入门逆向，对qq逆向毫无办法

**Comment by 18351089214** [comment]
可以看下readme文件，没有涉及到逆向破解方面

**Comment by 18351089214** [comment]
Hi,
你好，我github上有个project是关于微博自动登陆的，有逆向破解的一些东西，你可以看下。
如果有什么问题，大家一起交流讨论下！
